// Generated by gencpp from file custom/add.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGE_ADD_H
#define CUSTOM_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <custom/addRequest.h>
#include <custom/addResponse.h>


namespace custom
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom::add > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::custom::add&) { return value(); }
};

template<>
struct DataType< ::custom::add > {
  static const char* value()
  {
    return "custom/add";
  }

  static const char* value(const ::custom::add&) { return value(); }
};


// service_traits::MD5Sum< ::custom::addRequest> should match
// service_traits::MD5Sum< ::custom::add >
template<>
struct MD5Sum< ::custom::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom::add >::value();
  }
  static const char* value(const ::custom::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom::addRequest> should match
// service_traits::DataType< ::custom::add >
template<>
struct DataType< ::custom::addRequest>
{
  static const char* value()
  {
    return DataType< ::custom::add >::value();
  }
  static const char* value(const ::custom::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom::addResponse> should match
// service_traits::MD5Sum< ::custom::add >
template<>
struct MD5Sum< ::custom::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom::add >::value();
  }
  static const char* value(const ::custom::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom::addResponse> should match
// service_traits::DataType< ::custom::add >
template<>
struct DataType< ::custom::addResponse>
{
  static const char* value()
  {
    return DataType< ::custom::add >::value();
  }
  static const char* value(const ::custom::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MESSAGE_ADD_H
